### ISSUE TITLE
Exclude namespaces 

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/Network#10]
`exclude = User:Admin`
is working as expected.

 However, it would be great to have the possiblity to exclude namespaces generally.
Option 1: just via `exlude = User:`
Option 2: in a setting via LocalSettings

**Comment by JeroenDeDauw** [comment]
Should certain namespaces be excluded by default?

A sensible default might be to exclude all talk pages and user pages.

**Comment by krabina** [comment]
you might want to exclude Help: and File: pages as well. 
And of course there could be custom namespace.

A possibility would also be to look for content namespaces and use only these.
