### ISSUE TITLE
Title Icons In Network Diagram

### ISSUE THREAD

**Issue by wanjaus** [ProfessionalWiki/Network#57]
I was trying to find out if it is possible to have [Title Icons](https://www.mediawiki.org/wiki/Extension:Title_Icon) in the network diagram. This will make it easier to distinguish between the links. For instance, I have a wiki where I have links between organizations and people. From the network, one cannot tell which one is an organization and which is a person since all are just article titles. Title Icons would be a great way to achieve this.

**Comment by JeroenDeDauw** [comment]
Search for "title icon" in the README. In this section https://github.com/ProfessionalWiki/Network#node-icons

**Comment by wanjaus** [comment]
I have Title Icons V5.1 installed and the Title Icons are not rendering by default as the README suggests. From my understanding of the README, there is no configuration that should happen if Title Icons are version 5.1. The Title Icons are showing in other aspects of my Wiki like in search results and Page titles.

**Comment by JeroenDeDauw** [comment]
Ping @cicalese

**Comment by JeroenDeDauw** [comment]
@wanjaus actually, you did not report the version of network you use. Is it an older version? This functionality was only added in 2.0.

**Comment by wanjaus** [comment]
It actually works after I have upgraded to 2.0. On this [Page](https://github.com/ProfessionalWiki/Network#node-icons) has composer with Network 1.3, I have substituted that with 2.0. Thank you for assisting with the troubleshooting.
