### ISSUE TITLE
Redirects cause the visualization to break

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/Network#58]
Steps to reproduce 
* Go to https://maps.extension.wiki/wiki/Special:Network
* Put `Maps for MediaWiki` in the main box and submit
* Error in browser console

**Comment by sneakers-the-rat** [comment]
+1 on this, could help PR if devs pointed me to where the problem is happening :)

**Comment by squirrelslair** [comment]
The above comment says "closed" - but this still breaks, possibly for redirects. Will there be a fix?

**Comment by M-APatel1** [comment]
Hello @cicalese! Did you have a chance to look into this bug?
