### ISSUE TITLE
excludedNamespaces options does not work

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/Network#62]
the option `|excludedNamespaces`
does not seem to work. If I add "102" which is the "Property:" namespace of SMW, I still see the links. If I add "0", which would be the main namespace, I still see a lot of pages from the main namespace.

**Comment by JeroenDeDauw** [comment]
Added in https://github.com/ProfessionalWiki/Network/pull/29 by @cicalese

**Comment by krabina** [comment]
Just realized, I was using 1.4 of the extension. Sorry.
